name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Send JSON-RPC request '...'
        3. Observe error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
      placeholder: Instead, I got...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Proxy version
      description: Output of `bun-docs-mcp-proxy --version` or git commit hash
      placeholder: "0.2.1"
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust version
      description: Output of `rustc --version`
      placeholder: "rustc 1.81.0 (eeb90cda1 2024-09-04)"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What operating system are you using?
      options:
        - Linux x86_64
        - Linux ARM64
        - macOS Intel
        - macOS Apple Silicon
        - Windows
        - Other (specify in additional context)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please paste any relevant log output (run with `RUST_LOG=debug` for verbose logs)
      render: shell
      placeholder: |
        RUST_LOG=debug ./target/release/bun-docs-mcp-proxy
        ...

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here (screenshots, error messages, etc.)
