import { renderPlatformLines } from "./platforms";
import type { ReleaseNotesParams } from "./types";

const fallbackPlatformLines = [
  "- **Linux x86_64**: `bun-docs-mcp-proxy-linux-x86_64.tar.gz`",
  "- **Linux ARM64**: `bun-docs-mcp-proxy-linux-aarch64.tar.gz`",
  "- **Linux x86_64 musl** (static): `bun-docs-mcp-proxy-linux-x86_64-musl.tar.gz`",
  "- **Linux ARM64 musl** (static): `bun-docs-mcp-proxy-linux-aarch64-musl.tar.gz`",
  "- **macOS Intel**: `bun-docs-mcp-proxy-macos-x86_64.tar.gz`",
  "- **macOS Apple Silicon**: `bun-docs-mcp-proxy-macos-aarch64.tar.gz`",
  "- **Windows x86_64**: `bun-docs-mcp-proxy-windows-x86_64.zip`",
  "- **Windows ARM64**: `bun-docs-mcp-proxy-windows-aarch64.zip`",
];

export const buildReleaseNotes = ({
  version,
  repoFull,
  checksums,
  platforms,
}: ReleaseNotesParams): string => {
  const codeFence = "```";
  const platformLines = platforms.length > 0 ? renderPlatformLines(platforms) : fallbackPlatformLines;

  return [
    `## Bun Docs MCP Proxy ${version}`,
    "",
    "### Installation",
    "",
    "Download the binary for your platform below, extract it, and make it executable (Linux/macOS).",
    "",
    "#### Linux/macOS",
    "",
    `${codeFence}bash`,
    "# Download and extract (adjust URL for your platform)",
    `curl -L https://github.com/${repoFull}/releases/download/${version}/bun-docs-mcp-proxy-linux-x86_64.tar.gz | tar xz`,
    "",
    "# Make executable",
    "chmod +x bun-docs-mcp-proxy",
    "",
    "# Move to PATH (optional)",
    "sudo mv bun-docs-mcp-proxy /usr/local/bin/",
    codeFence,
    "",
    "#### Windows",
    "Download the `.zip` file, extract it, and add to your PATH.",
    "",
    "### Platforms",
    "",
    ...platformLines,
    "",
    "### Verification",
    "",
    "#### Automated Verification (Recommended)",
    "",
    "All binaries are signed with GitHub's attestation system for supply chain security:",
    "",
    `${codeFence}bash`,
    "# Install GitHub CLI if needed",
    "# gh --version",
    "",
    "# Verify attestation (replace with your platform's filename)",
    "gh attestation verify bun-docs-mcp-proxy-linux-x86_64.tar.gz --owner kjanat",
    codeFence,
    "",
    "#### Manual Verification",
    "",
    "Download `SHA256SUMS` and verify checksums:",
    "",
    `${codeFence}bash`,
    "# Linux/macOS",
    "sha256sum -c SHA256SUMS",
    "",
    "# Or verify single file",
    "sha256sum bun-docs-mcp-proxy-linux-x86_64.tar.gz",
    "",
    "# Windows (PowerShell)",
    "Get-FileHash bun-docs-mcp-proxy-windows-x86_64.zip -Algorithm SHA256",
    codeFence,
    "",
    "#### SHA256 Checksums",
    "",
    codeFence,
    checksums,
    codeFence,
    "",
  ].join("\n");
};
