# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: autofix.ci
on: { pull_request: {}, push: { branches: ["master"] } }
permissions: { contents: read }
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@v6 }
      - { uses: oven-sh/setup-bun@v2 }
      - { uses: ./.github/actions/rust-setup, with: { install-just: "false" } }

      - name: Install formatters
        run: bun i -g dprint tombi

      - name: Format all files
        run: dprint fmt --allow-no-files --excludes ".github"
        continue-on-error: true

      - name: Fix clippy warnings
        run: cargo clippy --fix --allow-dirty --allow-staged --workspace
        continue-on-error: true

      - uses: autofix-ci/action@v1
